# Generated by Django 3.1.1 on 2020-09-09 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default=None, max_length=64)),
                ('owner', models.CharField(default=None, max_length=64)),
                ('owner_phone', models.CharField(default=None, max_length=64)),
                ('user', models.CharField(default=None, max_length=64)),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 19, 43, 26, 637043))),
                ('due', models.DateTimeField(default=datetime.datetime(2020, 9, 9, 19, 43, 26, 637043))),
                ('location', models.CharField(default=None, max_length=64)),
                ('addition', models.CharField(default=None, max_length=64)),
                ('valid', models.CharField(default=None, max_length=64)),
                ('reason', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RentingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(default=0)),
                ('username', models.CharField(default=None, max_length=64)),
                ('reason', models.TextField(default=None, max_length=2000)),
                ('contact', models.TextField(default=None, max_length=64)),
                ('start', models.DateTimeField(default=None, max_length=64)),
                ('due', models.DateTimeField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=1000)),
                ('email', models.CharField(default=None, max_length=64)),
                ('contact', models.CharField(default=None, max_length=64)),
                ('identity', models.CharField(default=None, max_length=64)),
                ('apply', models.CharField(default=None, max_length=64)),
                ('token', models.CharField(default=None, max_length=64)),
            ],
        ),
    ]
