# Generated by Django 3.1.1 on 2020-09-09 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentingorder',
            name='valid',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 19, 58, 37, 902148)),
        ),
        migrations.AlterField(
            model_name='device',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 19, 58, 37, 902148)),
        ),
    ]
