# Generated by Django 3.1.1 on 2020-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200910_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='due',
        ),
        migrations.RemoveField(
            model_name='device',
            name='start',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='due',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='rent_end',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='rent_start',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='rent_state',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='start',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='shelforder',
            name='start_time',
            field=models.DateField(default=None, max_length=64),
        ),
    ]
