# Generated by Django 3.1.1 on 2020-09-10 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200910_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='due',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 22, 45, 31, 129649)),
        ),
        migrations.AlterField(
            model_name='device',
            name='start',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 22, 45, 31, 129649)),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='due',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='rent_end',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='rent_start',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='start',
            field=models.DateField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='shelforder',
            name='start_time',
            field=models.DateField(default=None, max_length=64),
        ),
    ]
