# Generated by Django 3.1.1 on 2020-09-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200910_2245'),
        ('database', '0006_auto_20200910_2323'),
    ]

    operations = [
    ]
