# Generated by Django 3.1.1 on 2020-09-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_merge_20200911_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelforder',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='user_id',
            field=models.IntegerField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='rentingorder',
            name='rent_state',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
