# Generated by Django 3.1.1 on 2020-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200912_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_from', models.CharField(default=None, max_length=64)),
                ('username_to', models.CharField(default=None, max_length=64)),
                ('content', models.TextField(default=None, max_length=2000)),
                ('time', models.DateTimeField(default=None, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='applyorder',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
