# Generated by Django 3.1.1 on 2020-09-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200910_1201'),
        ('database', '0010_auto_20200912_2148'),
    ]

    operations = [
    ]
