# Generated by Django 3.1.1 on 2020-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200912_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=64)),
                ('device_id', models.IntegerField(default=None, max_length=64)),
                ('device_name', models.CharField(default=None, max_length=64)),
                ('reason', models.TextField(default=None, max_length=2000)),
                ('time', models.DateTimeField(default=None, max_length=64)),
            ],
        ),
    ]
