# Generated by Django 3.1.1 on 2020-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_dialog_judgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='time',
            field=models.DateTimeField(default=None, max_length=64),
        ),
    ]
