# Generated by Django 3.1.1 on 2020-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_dialog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='device_id',
            field=models.IntegerField(default=None),
        ),
    ]
